name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Run ESLint
        run: pnpm lint
